/**
 * Generated by Scrooge
 *   version: 4.16.0-SNAPSHOT
 *   rev: eb110c820bcd2734b26023f24d636bf6d37511b3
 *   built at: 20170607-185808
 */
package parquet.format

import com.twitter.io.Buf
import com.twitter.scrooge.{
  HasThriftStructCodec3,
  LazyTProtocol,
  TFieldBlob,
  ThriftException,
  ThriftStruct,
  ThriftStructCodec3,
  ThriftStructFieldInfo,
  ThriftStructMetaData,
  ThriftUtil
}
import org.apache.thrift.protocol._
import org.apache.thrift.transport.{TMemoryBuffer, TTransport, TIOStreamTransport}
import java.io.ByteArrayInputStream
import java.nio.ByteBuffer
import java.util.Arrays
import java.util.concurrent.atomic.AtomicInteger
import scala.collection.immutable.{Map => immutable$Map}
import scala.collection.mutable.Builder
import scala.collection.mutable.{
  ArrayBuffer => mutable$ArrayBuffer, Buffer => mutable$Buffer,
  HashMap => mutable$HashMap, HashSet => mutable$HashSet}
import scala.collection.{Map, Set}

/** Data page header */
object DataPageHeader extends ThriftStructCodec3[DataPageHeader] {
  val NoPassthroughFields: immutable$Map[Short, TFieldBlob] = immutable$Map.empty[Short, TFieldBlob]
  val Struct = new TStruct("DataPageHeader")
  val NumValuesField = new TField("num_values", TType.I32, 1)
  val NumValuesFieldManifest = implicitly[Manifest[Int]]
  val EncodingField = new TField("encoding", TType.ENUM, 2)
  val EncodingFieldI32 = new TField("encoding", TType.I32, 2)
  val EncodingFieldManifest = implicitly[Manifest[parquet.format.Encoding]]
  val DefinitionLevelEncodingField = new TField("definition_level_encoding", TType.ENUM, 3)
  val DefinitionLevelEncodingFieldI32 = new TField("definition_level_encoding", TType.I32, 3)
  val DefinitionLevelEncodingFieldManifest = implicitly[Manifest[parquet.format.Encoding]]
  val RepetitionLevelEncodingField = new TField("repetition_level_encoding", TType.ENUM, 4)
  val RepetitionLevelEncodingFieldI32 = new TField("repetition_level_encoding", TType.I32, 4)
  val RepetitionLevelEncodingFieldManifest = implicitly[Manifest[parquet.format.Encoding]]
  val StatisticsField = new TField("statistics", TType.STRUCT, 5)
  val StatisticsFieldManifest = implicitly[Manifest[parquet.format.Statistics]]

  /**
   * Field information in declaration order.
   */
  lazy val fieldInfos: scala.List[ThriftStructFieldInfo] = scala.List[ThriftStructFieldInfo](
    new ThriftStructFieldInfo(
      NumValuesField,
      false,
      true,
      NumValuesFieldManifest,
      _root_.scala.None,
      _root_.scala.None,
      immutable$Map.empty[String, String],
      immutable$Map.empty[String, String],
      None
    ),
    new ThriftStructFieldInfo(
      EncodingField,
      false,
      true,
      EncodingFieldManifest,
      _root_.scala.None,
      _root_.scala.None,
      immutable$Map.empty[String, String],
      immutable$Map.empty[String, String],
      None
    ),
    new ThriftStructFieldInfo(
      DefinitionLevelEncodingField,
      false,
      true,
      DefinitionLevelEncodingFieldManifest,
      _root_.scala.None,
      _root_.scala.None,
      immutable$Map.empty[String, String],
      immutable$Map.empty[String, String],
      None
    ),
    new ThriftStructFieldInfo(
      RepetitionLevelEncodingField,
      false,
      true,
      RepetitionLevelEncodingFieldManifest,
      _root_.scala.None,
      _root_.scala.None,
      immutable$Map.empty[String, String],
      immutable$Map.empty[String, String],
      None
    ),
    new ThriftStructFieldInfo(
      StatisticsField,
      true,
      false,
      StatisticsFieldManifest,
      _root_.scala.None,
      _root_.scala.None,
      immutable$Map.empty[String, String],
      immutable$Map.empty[String, String],
      None
    )
  )

  lazy val structAnnotations: immutable$Map[String, String] =
    immutable$Map.empty[String, String]

  /**
   * Checks that all required fields are non-null.
   */
  def validate(_item: DataPageHeader): Unit = {
    if (_item.encoding == null) throw new TProtocolException("Required field encoding cannot be null")
    if (_item.definitionLevelEncoding == null) throw new TProtocolException("Required field definitionLevelEncoding cannot be null")
    if (_item.repetitionLevelEncoding == null) throw new TProtocolException("Required field repetitionLevelEncoding cannot be null")
  }

  def withoutPassthroughFields(original: DataPageHeader): DataPageHeader =
    new Immutable(
      numValues =
        {
          val field = original.numValues
          field
        },
      encoding =
        {
          val field = original.encoding
          field
        },
      definitionLevelEncoding =
        {
          val field = original.definitionLevelEncoding
          field
        },
      repetitionLevelEncoding =
        {
          val field = original.repetitionLevelEncoding
          field
        },
      statistics =
        {
          val field = original.statistics
          field.map { field =>
            parquet.format.Statistics.withoutPassthroughFields(field)
          }
        }
    )

  override def encode(_item: DataPageHeader, _oproto: TProtocol): Unit = {
    _item.write(_oproto)
  }


  private[this] def lazyDecode(_iprot: LazyTProtocol): DataPageHeader = {

    var numValues: Int = 0
    var _got_numValues = false
    var encoding: parquet.format.Encoding = null
    var _got_encoding = false
    var definitionLevelEncoding: parquet.format.Encoding = null
    var _got_definitionLevelEncoding = false
    var repetitionLevelEncoding: parquet.format.Encoding = null
    var _got_repetitionLevelEncoding = false
    var statistics: Option[parquet.format.Statistics] = None

    var _passthroughFields: Builder[(Short, TFieldBlob), immutable$Map[Short, TFieldBlob]] = null
    var _done = false
    val _start_offset = _iprot.offset

    _iprot.readStructBegin()
    while (!_done) {
      val _field = _iprot.readFieldBegin()
      if (_field.`type` == TType.STOP) {
        _done = true
      } else {
        _field.id match {
          case 1 =>
            _field.`type` match {
              case TType.I32 =>
    
                numValues = readNumValuesValue(_iprot)
                _got_numValues = true
              case _actualType =>
                val _expectedType = TType.I32
                throw new TProtocolException(
                  "Received wrong type for field 'numValues' (expected=%s, actual=%s).".format(
                    ttypeToString(_expectedType),
                    ttypeToString(_actualType)
                  )
                )
            }
          case 2 =>
            _field.`type` match {
              case TType.I32 | TType.ENUM =>
    
                encoding = readEncodingValue(_iprot)
                _got_encoding = true
              case _actualType =>
                val _expectedType = TType.ENUM
                throw new TProtocolException(
                  "Received wrong type for field 'encoding' (expected=%s, actual=%s).".format(
                    ttypeToString(_expectedType),
                    ttypeToString(_actualType)
                  )
                )
            }
          case 3 =>
            _field.`type` match {
              case TType.I32 | TType.ENUM =>
    
                definitionLevelEncoding = readDefinitionLevelEncodingValue(_iprot)
                _got_definitionLevelEncoding = true
              case _actualType =>
                val _expectedType = TType.ENUM
                throw new TProtocolException(
                  "Received wrong type for field 'definitionLevelEncoding' (expected=%s, actual=%s).".format(
                    ttypeToString(_expectedType),
                    ttypeToString(_actualType)
                  )
                )
            }
          case 4 =>
            _field.`type` match {
              case TType.I32 | TType.ENUM =>
    
                repetitionLevelEncoding = readRepetitionLevelEncodingValue(_iprot)
                _got_repetitionLevelEncoding = true
              case _actualType =>
                val _expectedType = TType.ENUM
                throw new TProtocolException(
                  "Received wrong type for field 'repetitionLevelEncoding' (expected=%s, actual=%s).".format(
                    ttypeToString(_expectedType),
                    ttypeToString(_actualType)
                  )
                )
            }
          case 5 =>
            _field.`type` match {
              case TType.STRUCT =>
    
                statistics = Some(readStatisticsValue(_iprot))
              case _actualType =>
                val _expectedType = TType.STRUCT
                throw new TProtocolException(
                  "Received wrong type for field 'statistics' (expected=%s, actual=%s).".format(
                    ttypeToString(_expectedType),
                    ttypeToString(_actualType)
                  )
                )
            }
          case _ =>
            if (_passthroughFields == null)
              _passthroughFields = immutable$Map.newBuilder[Short, TFieldBlob]
            _passthroughFields += (_field.id -> TFieldBlob.read(_field, _iprot))
        }
        _iprot.readFieldEnd()
      }
    }
    _iprot.readStructEnd()

    if (!_got_numValues) throw new TProtocolException("Required field 'numValues' was not found in serialized data for struct DataPageHeader")
    if (!_got_encoding) throw new TProtocolException("Required field 'encoding' was not found in serialized data for struct DataPageHeader")
    if (!_got_definitionLevelEncoding) throw new TProtocolException("Required field 'definitionLevelEncoding' was not found in serialized data for struct DataPageHeader")
    if (!_got_repetitionLevelEncoding) throw new TProtocolException("Required field 'repetitionLevelEncoding' was not found in serialized data for struct DataPageHeader")
    new LazyImmutable(
      _iprot,
      _iprot.buffer,
      _start_offset,
      _iprot.offset,
      numValues,
      encoding,
      definitionLevelEncoding,
      repetitionLevelEncoding,
      statistics,
      if (_passthroughFields == null)
        NoPassthroughFields
      else
        _passthroughFields.result()
    )
  }

  override def decode(_iprot: TProtocol): DataPageHeader =
    _iprot match {
      case i: LazyTProtocol => lazyDecode(i)
      case i => eagerDecode(i)
    }

  private[format] def eagerDecode(_iprot: TProtocol): DataPageHeader = {
    var numValues: Int = 0
    var _got_numValues = false
    var encoding: parquet.format.Encoding = null
    var _got_encoding = false
    var definitionLevelEncoding: parquet.format.Encoding = null
    var _got_definitionLevelEncoding = false
    var repetitionLevelEncoding: parquet.format.Encoding = null
    var _got_repetitionLevelEncoding = false
    var statistics: _root_.scala.Option[parquet.format.Statistics] = _root_.scala.None
    var _passthroughFields: Builder[(Short, TFieldBlob), immutable$Map[Short, TFieldBlob]] = null
    var _done = false

    _iprot.readStructBegin()
    while (!_done) {
      val _field = _iprot.readFieldBegin()
      if (_field.`type` == TType.STOP) {
        _done = true
      } else {
        _field.id match {
          case 1 =>
            _field.`type` match {
              case TType.I32 =>
                numValues = readNumValuesValue(_iprot)
                _got_numValues = true
              case _actualType =>
                val _expectedType = TType.I32
                throw new TProtocolException(
                  "Received wrong type for field 'numValues' (expected=%s, actual=%s).".format(
                    ttypeToString(_expectedType),
                    ttypeToString(_actualType)
                  )
                )
            }
          case 2 =>
            _field.`type` match {
              case TType.I32 | TType.ENUM =>
                encoding = readEncodingValue(_iprot)
                _got_encoding = true
              case _actualType =>
                val _expectedType = TType.ENUM
                throw new TProtocolException(
                  "Received wrong type for field 'encoding' (expected=%s, actual=%s).".format(
                    ttypeToString(_expectedType),
                    ttypeToString(_actualType)
                  )
                )
            }
          case 3 =>
            _field.`type` match {
              case TType.I32 | TType.ENUM =>
                definitionLevelEncoding = readDefinitionLevelEncodingValue(_iprot)
                _got_definitionLevelEncoding = true
              case _actualType =>
                val _expectedType = TType.ENUM
                throw new TProtocolException(
                  "Received wrong type for field 'definitionLevelEncoding' (expected=%s, actual=%s).".format(
                    ttypeToString(_expectedType),
                    ttypeToString(_actualType)
                  )
                )
            }
          case 4 =>
            _field.`type` match {
              case TType.I32 | TType.ENUM =>
                repetitionLevelEncoding = readRepetitionLevelEncodingValue(_iprot)
                _got_repetitionLevelEncoding = true
              case _actualType =>
                val _expectedType = TType.ENUM
                throw new TProtocolException(
                  "Received wrong type for field 'repetitionLevelEncoding' (expected=%s, actual=%s).".format(
                    ttypeToString(_expectedType),
                    ttypeToString(_actualType)
                  )
                )
            }
          case 5 =>
            _field.`type` match {
              case TType.STRUCT =>
                statistics = _root_.scala.Some(readStatisticsValue(_iprot))
              case _actualType =>
                val _expectedType = TType.STRUCT
                throw new TProtocolException(
                  "Received wrong type for field 'statistics' (expected=%s, actual=%s).".format(
                    ttypeToString(_expectedType),
                    ttypeToString(_actualType)
                  )
                )
            }
          case _ =>
            if (_passthroughFields == null)
              _passthroughFields = immutable$Map.newBuilder[Short, TFieldBlob]
            _passthroughFields += (_field.id -> TFieldBlob.read(_field, _iprot))
        }
        _iprot.readFieldEnd()
      }
    }
    _iprot.readStructEnd()

    if (!_got_numValues) throw new TProtocolException("Required field 'numValues' was not found in serialized data for struct DataPageHeader")
    if (!_got_encoding) throw new TProtocolException("Required field 'encoding' was not found in serialized data for struct DataPageHeader")
    if (!_got_definitionLevelEncoding) throw new TProtocolException("Required field 'definitionLevelEncoding' was not found in serialized data for struct DataPageHeader")
    if (!_got_repetitionLevelEncoding) throw new TProtocolException("Required field 'repetitionLevelEncoding' was not found in serialized data for struct DataPageHeader")
    new Immutable(
      numValues,
      encoding,
      definitionLevelEncoding,
      repetitionLevelEncoding,
      statistics,
      if (_passthroughFields == null)
        NoPassthroughFields
      else
        _passthroughFields.result()
    )
  }

  def apply(
    numValues: Int,
    encoding: parquet.format.Encoding,
    definitionLevelEncoding: parquet.format.Encoding,
    repetitionLevelEncoding: parquet.format.Encoding,
    statistics: _root_.scala.Option[parquet.format.Statistics] = _root_.scala.None
  ): DataPageHeader =
    new Immutable(
      numValues,
      encoding,
      definitionLevelEncoding,
      repetitionLevelEncoding,
      statistics
    )

  def unapply(_item: DataPageHeader): _root_.scala.Option[_root_.scala.Tuple5[Int, parquet.format.Encoding, parquet.format.Encoding, parquet.format.Encoding, Option[parquet.format.Statistics]]] = _root_.scala.Some(_item.toTuple)


  @inline private[format] def readNumValuesValue(_iprot: TProtocol): Int = {
    _iprot.readI32()
  }

  @inline private def writeNumValuesField(numValues_item: Int, _oprot: TProtocol): Unit = {
    _oprot.writeFieldBegin(NumValuesField)
    writeNumValuesValue(numValues_item, _oprot)
    _oprot.writeFieldEnd()
  }

  @inline private def writeNumValuesValue(numValues_item: Int, _oprot: TProtocol): Unit = {
    _oprot.writeI32(numValues_item)
  }

  @inline private[format] def readEncodingValue(_iprot: TProtocol): parquet.format.Encoding = {
    parquet.format.Encoding.getOrUnknown(_iprot.readI32())
  }

  @inline private def writeEncodingField(encoding_item: parquet.format.Encoding, _oprot: TProtocol): Unit = {
    _oprot.writeFieldBegin(EncodingFieldI32)
    writeEncodingValue(encoding_item, _oprot)
    _oprot.writeFieldEnd()
  }

  @inline private def writeEncodingValue(encoding_item: parquet.format.Encoding, _oprot: TProtocol): Unit = {
    _oprot.writeI32(encoding_item.value)
  }

  @inline private[format] def readDefinitionLevelEncodingValue(_iprot: TProtocol): parquet.format.Encoding = {
    parquet.format.Encoding.getOrUnknown(_iprot.readI32())
  }

  @inline private def writeDefinitionLevelEncodingField(definitionLevelEncoding_item: parquet.format.Encoding, _oprot: TProtocol): Unit = {
    _oprot.writeFieldBegin(DefinitionLevelEncodingFieldI32)
    writeDefinitionLevelEncodingValue(definitionLevelEncoding_item, _oprot)
    _oprot.writeFieldEnd()
  }

  @inline private def writeDefinitionLevelEncodingValue(definitionLevelEncoding_item: parquet.format.Encoding, _oprot: TProtocol): Unit = {
    _oprot.writeI32(definitionLevelEncoding_item.value)
  }

  @inline private[format] def readRepetitionLevelEncodingValue(_iprot: TProtocol): parquet.format.Encoding = {
    parquet.format.Encoding.getOrUnknown(_iprot.readI32())
  }

  @inline private def writeRepetitionLevelEncodingField(repetitionLevelEncoding_item: parquet.format.Encoding, _oprot: TProtocol): Unit = {
    _oprot.writeFieldBegin(RepetitionLevelEncodingFieldI32)
    writeRepetitionLevelEncodingValue(repetitionLevelEncoding_item, _oprot)
    _oprot.writeFieldEnd()
  }

  @inline private def writeRepetitionLevelEncodingValue(repetitionLevelEncoding_item: parquet.format.Encoding, _oprot: TProtocol): Unit = {
    _oprot.writeI32(repetitionLevelEncoding_item.value)
  }

  @inline private[format] def readStatisticsValue(_iprot: TProtocol): parquet.format.Statistics = {
    parquet.format.Statistics.decode(_iprot)
  }

  @inline private def writeStatisticsField(statistics_item: parquet.format.Statistics, _oprot: TProtocol): Unit = {
    _oprot.writeFieldBegin(StatisticsField)
    writeStatisticsValue(statistics_item, _oprot)
    _oprot.writeFieldEnd()
  }

  @inline private def writeStatisticsValue(statistics_item: parquet.format.Statistics, _oprot: TProtocol): Unit = {
    statistics_item.write(_oprot)
  }


  object Immutable extends ThriftStructCodec3[DataPageHeader] {
    override def encode(_item: DataPageHeader, _oproto: TProtocol): Unit = { _item.write(_oproto) }
    override def decode(_iprot: TProtocol): DataPageHeader = DataPageHeader.decode(_iprot)
    override lazy val metaData: ThriftStructMetaData[DataPageHeader] = DataPageHeader.metaData
  }

  /**
   * The default read-only implementation of DataPageHeader.  You typically should not need to
   * directly reference this class; instead, use the DataPageHeader.apply method to construct
   * new instances.
   */
  class Immutable(
      val numValues: Int,
      val encoding: parquet.format.Encoding,
      val definitionLevelEncoding: parquet.format.Encoding,
      val repetitionLevelEncoding: parquet.format.Encoding,
      val statistics: _root_.scala.Option[parquet.format.Statistics],
      override val _passthroughFields: immutable$Map[Short, TFieldBlob])
    extends DataPageHeader {
    def this(
      numValues: Int,
      encoding: parquet.format.Encoding,
      definitionLevelEncoding: parquet.format.Encoding,
      repetitionLevelEncoding: parquet.format.Encoding,
      statistics: _root_.scala.Option[parquet.format.Statistics] = _root_.scala.None
    ) = this(
      numValues,
      encoding,
      definitionLevelEncoding,
      repetitionLevelEncoding,
      statistics,
      Map.empty
    )
  }

  /**
   * This is another Immutable, this however keeps strings as lazy values that are lazily decoded from the backing
   * array byte on read.
   */
  private[this] class LazyImmutable(
      _proto: LazyTProtocol,
      _buf: Array[Byte],
      _start_offset: Int,
      _end_offset: Int,
      val numValues: Int,
      val encoding: parquet.format.Encoding,
      val definitionLevelEncoding: parquet.format.Encoding,
      val repetitionLevelEncoding: parquet.format.Encoding,
      val statistics: _root_.scala.Option[parquet.format.Statistics],
      override val _passthroughFields: immutable$Map[Short, TFieldBlob])
    extends DataPageHeader {

    override def write(_oprot: TProtocol): Unit = {
      _oprot match {
        case i: LazyTProtocol => i.writeRaw(_buf, _start_offset, _end_offset - _start_offset)
        case _ => super.write(_oprot)
      }
    }


    /**
     * Override the super hash code to make it a lazy val rather than def.
     *
     * Calculating the hash code can be expensive, caching it where possible
     * can provide significant performance wins. (Key in a hash map for instance)
     * Usually not safe since the normal constructor will accept a mutable map or
     * set as an arg
     * Here however we control how the class is generated from serialized data.
     * With the class private and the contract that we throw away our mutable references
     * having the hash code lazy here is safe.
     */
    override lazy val hashCode = super.hashCode
  }

  /**
   * This Proxy trait allows you to extend the DataPageHeader trait with additional state or
   * behavior and implement the read-only methods from DataPageHeader using an underlying
   * instance.
   */
  trait Proxy extends DataPageHeader {
    protected def _underlying_DataPageHeader: DataPageHeader
    override def numValues: Int = _underlying_DataPageHeader.numValues
    override def encoding: parquet.format.Encoding = _underlying_DataPageHeader.encoding
    override def definitionLevelEncoding: parquet.format.Encoding = _underlying_DataPageHeader.definitionLevelEncoding
    override def repetitionLevelEncoding: parquet.format.Encoding = _underlying_DataPageHeader.repetitionLevelEncoding
    override def statistics: _root_.scala.Option[parquet.format.Statistics] = _underlying_DataPageHeader.statistics
    override def _passthroughFields = _underlying_DataPageHeader._passthroughFields
  }
}

/**
 * Prefer the companion object's [[parquet.format.DataPageHeader.apply]]
 * for construction if you don't need to specify passthrough fields.
 */
trait DataPageHeader
  extends ThriftStruct
  with _root_.scala.Product5[Int, parquet.format.Encoding, parquet.format.Encoding, parquet.format.Encoding, Option[parquet.format.Statistics]]
  with HasThriftStructCodec3[DataPageHeader]
  with java.io.Serializable
{
  import DataPageHeader._

  def numValues: Int
  def encoding: parquet.format.Encoding
  def definitionLevelEncoding: parquet.format.Encoding
  def repetitionLevelEncoding: parquet.format.Encoding
  def statistics: _root_.scala.Option[parquet.format.Statistics]

  def _passthroughFields: immutable$Map[Short, TFieldBlob] = immutable$Map.empty

  def _1 = numValues
  def _2 = encoding
  def _3 = definitionLevelEncoding
  def _4 = repetitionLevelEncoding
  def _5 = statistics

  def toTuple: _root_.scala.Tuple5[Int, parquet.format.Encoding, parquet.format.Encoding, parquet.format.Encoding, Option[parquet.format.Statistics]] = {
    (
      numValues,
      encoding,
      definitionLevelEncoding,
      repetitionLevelEncoding,
      statistics
    )
  }


  /**
   * Gets a field value encoded as a binary blob using TCompactProtocol.  If the specified field
   * is present in the passthrough map, that value is returned.  Otherwise, if the specified field
   * is known and not optional and set to None, then the field is serialized and returned.
   */
  def getFieldBlob(_fieldId: Short): _root_.scala.Option[TFieldBlob] = {
    lazy val _buff = new TMemoryBuffer(32)
    lazy val _oprot = new TCompactProtocol(_buff)
    _passthroughFields.get(_fieldId) match {
      case blob: _root_.scala.Some[TFieldBlob] => blob
      case _root_.scala.None => {
        val _fieldOpt: _root_.scala.Option[TField] =
          _fieldId match {
            case 1 =>
              if (true) {
                writeNumValuesValue(numValues, _oprot)
                _root_.scala.Some(DataPageHeader.NumValuesField)
              } else {
                _root_.scala.None
              }
            case 2 =>
              if (encoding ne null) {
                writeEncodingValue(encoding, _oprot)
                _root_.scala.Some(DataPageHeader.EncodingField)
              } else {
                _root_.scala.None
              }
            case 3 =>
              if (definitionLevelEncoding ne null) {
                writeDefinitionLevelEncodingValue(definitionLevelEncoding, _oprot)
                _root_.scala.Some(DataPageHeader.DefinitionLevelEncodingField)
              } else {
                _root_.scala.None
              }
            case 4 =>
              if (repetitionLevelEncoding ne null) {
                writeRepetitionLevelEncodingValue(repetitionLevelEncoding, _oprot)
                _root_.scala.Some(DataPageHeader.RepetitionLevelEncodingField)
              } else {
                _root_.scala.None
              }
            case 5 =>
              if (statistics.isDefined) {
                writeStatisticsValue(statistics.get, _oprot)
                _root_.scala.Some(DataPageHeader.StatisticsField)
              } else {
                _root_.scala.None
              }
            case _ => _root_.scala.None
          }
        _fieldOpt match {
          case _root_.scala.Some(_field) =>
            _root_.scala.Some(TFieldBlob(_field, Buf.ByteArray.Owned(_buff.getArray())))
          case _root_.scala.None =>
            _root_.scala.None
        }
      }
    }
  }

  /**
   * Collects TCompactProtocol-encoded field values according to `getFieldBlob` into a map.
   */
  def getFieldBlobs(ids: TraversableOnce[Short]): immutable$Map[Short, TFieldBlob] =
    (ids flatMap { id => getFieldBlob(id) map { id -> _ } }).toMap

  /**
   * Sets a field using a TCompactProtocol-encoded binary blob.  If the field is a known
   * field, the blob is decoded and the field is set to the decoded value.  If the field
   * is unknown and passthrough fields are enabled, then the blob will be stored in
   * _passthroughFields.
   */
  def setField(_blob: TFieldBlob): DataPageHeader = {
    var numValues: Int = this.numValues
    var encoding: parquet.format.Encoding = this.encoding
    var definitionLevelEncoding: parquet.format.Encoding = this.definitionLevelEncoding
    var repetitionLevelEncoding: parquet.format.Encoding = this.repetitionLevelEncoding
    var statistics: _root_.scala.Option[parquet.format.Statistics] = this.statistics
    var _passthroughFields = this._passthroughFields
    _blob.id match {
      case 1 =>
        numValues = readNumValuesValue(_blob.read)
      case 2 =>
        encoding = readEncodingValue(_blob.read)
      case 3 =>
        definitionLevelEncoding = readDefinitionLevelEncodingValue(_blob.read)
      case 4 =>
        repetitionLevelEncoding = readRepetitionLevelEncodingValue(_blob.read)
      case 5 =>
        statistics = _root_.scala.Some(readStatisticsValue(_blob.read))
      case _ => _passthroughFields += (_blob.id -> _blob)
    }
    new Immutable(
      numValues,
      encoding,
      definitionLevelEncoding,
      repetitionLevelEncoding,
      statistics,
      _passthroughFields
    )
  }

  /**
   * If the specified field is optional, it is set to None.  Otherwise, if the field is
   * known, it is reverted to its default value; if the field is unknown, it is removed
   * from the passthroughFields map, if present.
   */
  def unsetField(_fieldId: Short): DataPageHeader = {
    var numValues: Int = this.numValues
    var encoding: parquet.format.Encoding = this.encoding
    var definitionLevelEncoding: parquet.format.Encoding = this.definitionLevelEncoding
    var repetitionLevelEncoding: parquet.format.Encoding = this.repetitionLevelEncoding
    var statistics: _root_.scala.Option[parquet.format.Statistics] = this.statistics

    _fieldId match {
      case 1 =>
        numValues = 0
      case 2 =>
        encoding = null
      case 3 =>
        definitionLevelEncoding = null
      case 4 =>
        repetitionLevelEncoding = null
      case 5 =>
        statistics = _root_.scala.None
      case _ =>
    }
    new Immutable(
      numValues,
      encoding,
      definitionLevelEncoding,
      repetitionLevelEncoding,
      statistics,
      _passthroughFields - _fieldId
    )
  }

  /**
   * If the specified field is optional, it is set to None.  Otherwise, if the field is
   * known, it is reverted to its default value; if the field is unknown, it is removed
   * from the passthroughFields map, if present.
   */
  def unsetNumValues: DataPageHeader = unsetField(1)

  def unsetEncoding: DataPageHeader = unsetField(2)

  def unsetDefinitionLevelEncoding: DataPageHeader = unsetField(3)

  def unsetRepetitionLevelEncoding: DataPageHeader = unsetField(4)

  def unsetStatistics: DataPageHeader = unsetField(5)


  override def write(_oprot: TProtocol): Unit = {
    DataPageHeader.validate(this)
    _oprot.writeStructBegin(Struct)
    writeNumValuesField(numValues, _oprot)
    if (encoding ne null) writeEncodingField(encoding, _oprot)
    if (definitionLevelEncoding ne null) writeDefinitionLevelEncodingField(definitionLevelEncoding, _oprot)
    if (repetitionLevelEncoding ne null) writeRepetitionLevelEncodingField(repetitionLevelEncoding, _oprot)
    if (statistics.isDefined) writeStatisticsField(statistics.get, _oprot)
    if (_passthroughFields.nonEmpty) {
      _passthroughFields.values.foreach { _.write(_oprot) }
    }
    _oprot.writeFieldStop()
    _oprot.writeStructEnd()
  }

  def copy(
    numValues: Int = this.numValues,
    encoding: parquet.format.Encoding = this.encoding,
    definitionLevelEncoding: parquet.format.Encoding = this.definitionLevelEncoding,
    repetitionLevelEncoding: parquet.format.Encoding = this.repetitionLevelEncoding,
    statistics: _root_.scala.Option[parquet.format.Statistics] = this.statistics,
    _passthroughFields: immutable$Map[Short, TFieldBlob] = this._passthroughFields
  ): DataPageHeader =
    new Immutable(
      numValues,
      encoding,
      definitionLevelEncoding,
      repetitionLevelEncoding,
      statistics,
      _passthroughFields
    )

  override def canEqual(other: Any): Boolean = other.isInstanceOf[DataPageHeader]

  private def _equals(x: DataPageHeader, y: DataPageHeader): Boolean =
      x.productArity == y.productArity &&
      x.productIterator.sameElements(y.productIterator)

  override def equals(other: Any): Boolean =
    canEqual(other) &&
      _equals(this, other.asInstanceOf[DataPageHeader]) &&
      _passthroughFields == other.asInstanceOf[DataPageHeader]._passthroughFields

  override def hashCode: Int = _root_.scala.runtime.ScalaRunTime._hashCode(this)

  override def toString: String = _root_.scala.runtime.ScalaRunTime._toString(this)


  override def productArity: Int = 5

  override def productElement(n: Int): Any = n match {
    case 0 => this.numValues
    case 1 => this.encoding
    case 2 => this.definitionLevelEncoding
    case 3 => this.repetitionLevelEncoding
    case 4 => this.statistics
    case _ => throw new IndexOutOfBoundsException(n.toString)
  }

  override def productPrefix: String = "DataPageHeader"

  def _codec: ThriftStructCodec3[DataPageHeader] = DataPageHeader
}

