/**
 * Generated by Scrooge
 *   version: 4.16.0-SNAPSHOT
 *   rev: eb110c820bcd2734b26023f24d636bf6d37511b3
 *   built at: 20170607-185808
 */
package parquet.format

import com.twitter.io.Buf
import com.twitter.scrooge.{
  HasThriftStructCodec3,
  LazyTProtocol,
  TFieldBlob,
  ThriftException,
  ThriftStruct,
  ThriftStructCodec3,
  ThriftStructFieldInfo,
  ThriftStructMetaData,
  ThriftUtil
}
import org.apache.thrift.protocol._
import org.apache.thrift.transport.{TMemoryBuffer, TTransport, TIOStreamTransport}
import java.io.ByteArrayInputStream
import java.nio.ByteBuffer
import java.util.Arrays
import java.util.concurrent.atomic.AtomicInteger
import scala.collection.immutable.{Map => immutable$Map}
import scala.collection.mutable.Builder
import scala.collection.mutable.{
  ArrayBuffer => mutable$ArrayBuffer, Buffer => mutable$Buffer,
  HashMap => mutable$HashMap, HashSet => mutable$HashSet}
import scala.collection.{Map, Set}


object DictionaryPageHeader extends ThriftStructCodec3[DictionaryPageHeader] {
  val NoPassthroughFields: immutable$Map[Short, TFieldBlob] = immutable$Map.empty[Short, TFieldBlob]
  val Struct = new TStruct("DictionaryPageHeader")
  val NumValuesField = new TField("num_values", TType.I32, 1)
  val NumValuesFieldManifest = implicitly[Manifest[Int]]
  val EncodingField = new TField("encoding", TType.ENUM, 2)
  val EncodingFieldI32 = new TField("encoding", TType.I32, 2)
  val EncodingFieldManifest = implicitly[Manifest[parquet.format.Encoding]]
  val IsSortedField = new TField("is_sorted", TType.BOOL, 3)
  val IsSortedFieldManifest = implicitly[Manifest[Boolean]]

  /**
   * Field information in declaration order.
   */
  lazy val fieldInfos: scala.List[ThriftStructFieldInfo] = scala.List[ThriftStructFieldInfo](
    new ThriftStructFieldInfo(
      NumValuesField,
      false,
      true,
      NumValuesFieldManifest,
      _root_.scala.None,
      _root_.scala.None,
      immutable$Map.empty[String, String],
      immutable$Map.empty[String, String],
      None
    ),
    new ThriftStructFieldInfo(
      EncodingField,
      false,
      true,
      EncodingFieldManifest,
      _root_.scala.None,
      _root_.scala.None,
      immutable$Map.empty[String, String],
      immutable$Map.empty[String, String],
      None
    ),
    new ThriftStructFieldInfo(
      IsSortedField,
      true,
      false,
      IsSortedFieldManifest,
      _root_.scala.None,
      _root_.scala.None,
      immutable$Map.empty[String, String],
      immutable$Map.empty[String, String],
      None
    )
  )

  lazy val structAnnotations: immutable$Map[String, String] =
    immutable$Map.empty[String, String]

  /**
   * Checks that all required fields are non-null.
   */
  def validate(_item: DictionaryPageHeader): Unit = {
    if (_item.encoding == null) throw new TProtocolException("Required field encoding cannot be null")
  }

  def withoutPassthroughFields(original: DictionaryPageHeader): DictionaryPageHeader =
    new Immutable(
      numValues =
        {
          val field = original.numValues
          field
        },
      encoding =
        {
          val field = original.encoding
          field
        },
      isSorted =
        {
          val field = original.isSorted
          field.map { field =>
            field
          }
        }
    )

  override def encode(_item: DictionaryPageHeader, _oproto: TProtocol): Unit = {
    _item.write(_oproto)
  }


  private[this] def lazyDecode(_iprot: LazyTProtocol): DictionaryPageHeader = {

    var numValues: Int = 0
    var _got_numValues = false
    var encoding: parquet.format.Encoding = null
    var _got_encoding = false
    var is_sortedOffset: Int = -1

    var _passthroughFields: Builder[(Short, TFieldBlob), immutable$Map[Short, TFieldBlob]] = null
    var _done = false
    val _start_offset = _iprot.offset

    _iprot.readStructBegin()
    while (!_done) {
      val _field = _iprot.readFieldBegin()
      if (_field.`type` == TType.STOP) {
        _done = true
      } else {
        _field.id match {
          case 1 =>
            _field.`type` match {
              case TType.I32 =>
    
                numValues = readNumValuesValue(_iprot)
                _got_numValues = true
              case _actualType =>
                val _expectedType = TType.I32
                throw new TProtocolException(
                  "Received wrong type for field 'numValues' (expected=%s, actual=%s).".format(
                    ttypeToString(_expectedType),
                    ttypeToString(_actualType)
                  )
                )
            }
          case 2 =>
            _field.`type` match {
              case TType.I32 | TType.ENUM =>
    
                encoding = readEncodingValue(_iprot)
                _got_encoding = true
              case _actualType =>
                val _expectedType = TType.ENUM
                throw new TProtocolException(
                  "Received wrong type for field 'encoding' (expected=%s, actual=%s).".format(
                    ttypeToString(_expectedType),
                    ttypeToString(_actualType)
                  )
                )
            }
          case 3 =>
            _field.`type` match {
              case TType.BOOL =>
                is_sortedOffset = _iprot.offsetSkipBool
    
              case _actualType =>
                val _expectedType = TType.BOOL
                throw new TProtocolException(
                  "Received wrong type for field 'isSorted' (expected=%s, actual=%s).".format(
                    ttypeToString(_expectedType),
                    ttypeToString(_actualType)
                  )
                )
            }
          case _ =>
            if (_passthroughFields == null)
              _passthroughFields = immutable$Map.newBuilder[Short, TFieldBlob]
            _passthroughFields += (_field.id -> TFieldBlob.read(_field, _iprot))
        }
        _iprot.readFieldEnd()
      }
    }
    _iprot.readStructEnd()

    if (!_got_numValues) throw new TProtocolException("Required field 'numValues' was not found in serialized data for struct DictionaryPageHeader")
    if (!_got_encoding) throw new TProtocolException("Required field 'encoding' was not found in serialized data for struct DictionaryPageHeader")
    new LazyImmutable(
      _iprot,
      _iprot.buffer,
      _start_offset,
      _iprot.offset,
      numValues,
      encoding,
      is_sortedOffset,
      if (_passthroughFields == null)
        NoPassthroughFields
      else
        _passthroughFields.result()
    )
  }

  override def decode(_iprot: TProtocol): DictionaryPageHeader =
    _iprot match {
      case i: LazyTProtocol => lazyDecode(i)
      case i => eagerDecode(i)
    }

  private[format] def eagerDecode(_iprot: TProtocol): DictionaryPageHeader = {
    var numValues: Int = 0
    var _got_numValues = false
    var encoding: parquet.format.Encoding = null
    var _got_encoding = false
    var isSorted: _root_.scala.Option[Boolean] = _root_.scala.None
    var _passthroughFields: Builder[(Short, TFieldBlob), immutable$Map[Short, TFieldBlob]] = null
    var _done = false

    _iprot.readStructBegin()
    while (!_done) {
      val _field = _iprot.readFieldBegin()
      if (_field.`type` == TType.STOP) {
        _done = true
      } else {
        _field.id match {
          case 1 =>
            _field.`type` match {
              case TType.I32 =>
                numValues = readNumValuesValue(_iprot)
                _got_numValues = true
              case _actualType =>
                val _expectedType = TType.I32
                throw new TProtocolException(
                  "Received wrong type for field 'numValues' (expected=%s, actual=%s).".format(
                    ttypeToString(_expectedType),
                    ttypeToString(_actualType)
                  )
                )
            }
          case 2 =>
            _field.`type` match {
              case TType.I32 | TType.ENUM =>
                encoding = readEncodingValue(_iprot)
                _got_encoding = true
              case _actualType =>
                val _expectedType = TType.ENUM
                throw new TProtocolException(
                  "Received wrong type for field 'encoding' (expected=%s, actual=%s).".format(
                    ttypeToString(_expectedType),
                    ttypeToString(_actualType)
                  )
                )
            }
          case 3 =>
            _field.`type` match {
              case TType.BOOL =>
                isSorted = _root_.scala.Some(readIsSortedValue(_iprot))
              case _actualType =>
                val _expectedType = TType.BOOL
                throw new TProtocolException(
                  "Received wrong type for field 'isSorted' (expected=%s, actual=%s).".format(
                    ttypeToString(_expectedType),
                    ttypeToString(_actualType)
                  )
                )
            }
          case _ =>
            if (_passthroughFields == null)
              _passthroughFields = immutable$Map.newBuilder[Short, TFieldBlob]
            _passthroughFields += (_field.id -> TFieldBlob.read(_field, _iprot))
        }
        _iprot.readFieldEnd()
      }
    }
    _iprot.readStructEnd()

    if (!_got_numValues) throw new TProtocolException("Required field 'numValues' was not found in serialized data for struct DictionaryPageHeader")
    if (!_got_encoding) throw new TProtocolException("Required field 'encoding' was not found in serialized data for struct DictionaryPageHeader")
    new Immutable(
      numValues,
      encoding,
      isSorted,
      if (_passthroughFields == null)
        NoPassthroughFields
      else
        _passthroughFields.result()
    )
  }

  def apply(
    numValues: Int,
    encoding: parquet.format.Encoding,
    isSorted: _root_.scala.Option[Boolean] = _root_.scala.None
  ): DictionaryPageHeader =
    new Immutable(
      numValues,
      encoding,
      isSorted
    )

  def unapply(_item: DictionaryPageHeader): _root_.scala.Option[_root_.scala.Tuple3[Int, parquet.format.Encoding, Option[Boolean]]] = _root_.scala.Some(_item.toTuple)


  @inline private[format] def readNumValuesValue(_iprot: TProtocol): Int = {
    _iprot.readI32()
  }

  @inline private def writeNumValuesField(numValues_item: Int, _oprot: TProtocol): Unit = {
    _oprot.writeFieldBegin(NumValuesField)
    writeNumValuesValue(numValues_item, _oprot)
    _oprot.writeFieldEnd()
  }

  @inline private def writeNumValuesValue(numValues_item: Int, _oprot: TProtocol): Unit = {
    _oprot.writeI32(numValues_item)
  }

  @inline private[format] def readEncodingValue(_iprot: TProtocol): parquet.format.Encoding = {
    parquet.format.Encoding.getOrUnknown(_iprot.readI32())
  }

  @inline private def writeEncodingField(encoding_item: parquet.format.Encoding, _oprot: TProtocol): Unit = {
    _oprot.writeFieldBegin(EncodingFieldI32)
    writeEncodingValue(encoding_item, _oprot)
    _oprot.writeFieldEnd()
  }

  @inline private def writeEncodingValue(encoding_item: parquet.format.Encoding, _oprot: TProtocol): Unit = {
    _oprot.writeI32(encoding_item.value)
  }

  @inline private[format] def readIsSortedValue(_iprot: TProtocol): Boolean = {
    _iprot.readBool()
  }

  @inline private def writeIsSortedField(isSorted_item: Boolean, _oprot: TProtocol): Unit = {
    _oprot.writeFieldBegin(IsSortedField)
    writeIsSortedValue(isSorted_item, _oprot)
    _oprot.writeFieldEnd()
  }

  @inline private def writeIsSortedValue(isSorted_item: Boolean, _oprot: TProtocol): Unit = {
    _oprot.writeBool(isSorted_item)
  }


  object Immutable extends ThriftStructCodec3[DictionaryPageHeader] {
    override def encode(_item: DictionaryPageHeader, _oproto: TProtocol): Unit = { _item.write(_oproto) }
    override def decode(_iprot: TProtocol): DictionaryPageHeader = DictionaryPageHeader.decode(_iprot)
    override lazy val metaData: ThriftStructMetaData[DictionaryPageHeader] = DictionaryPageHeader.metaData
  }

  /**
   * The default read-only implementation of DictionaryPageHeader.  You typically should not need to
   * directly reference this class; instead, use the DictionaryPageHeader.apply method to construct
   * new instances.
   */
  class Immutable(
      val numValues: Int,
      val encoding: parquet.format.Encoding,
      val isSorted: _root_.scala.Option[Boolean],
      override val _passthroughFields: immutable$Map[Short, TFieldBlob])
    extends DictionaryPageHeader {
    def this(
      numValues: Int,
      encoding: parquet.format.Encoding,
      isSorted: _root_.scala.Option[Boolean] = _root_.scala.None
    ) = this(
      numValues,
      encoding,
      isSorted,
      Map.empty
    )
  }

  /**
   * This is another Immutable, this however keeps strings as lazy values that are lazily decoded from the backing
   * array byte on read.
   */
  private[this] class LazyImmutable(
      _proto: LazyTProtocol,
      _buf: Array[Byte],
      _start_offset: Int,
      _end_offset: Int,
      val numValues: Int,
      val encoding: parquet.format.Encoding,
      is_sortedOffset: Int,
      override val _passthroughFields: immutable$Map[Short, TFieldBlob])
    extends DictionaryPageHeader {

    override def write(_oprot: TProtocol): Unit = {
      _oprot match {
        case i: LazyTProtocol => i.writeRaw(_buf, _start_offset, _end_offset - _start_offset)
        case _ => super.write(_oprot)
      }
    }

    lazy val isSorted: _root_.scala.Option[Boolean] =
      if (is_sortedOffset == -1)
        None
      else {
        Some(_proto.decodeBool(_buf, is_sortedOffset))
      }

    /**
     * Override the super hash code to make it a lazy val rather than def.
     *
     * Calculating the hash code can be expensive, caching it where possible
     * can provide significant performance wins. (Key in a hash map for instance)
     * Usually not safe since the normal constructor will accept a mutable map or
     * set as an arg
     * Here however we control how the class is generated from serialized data.
     * With the class private and the contract that we throw away our mutable references
     * having the hash code lazy here is safe.
     */
    override lazy val hashCode = super.hashCode
  }

  /**
   * This Proxy trait allows you to extend the DictionaryPageHeader trait with additional state or
   * behavior and implement the read-only methods from DictionaryPageHeader using an underlying
   * instance.
   */
  trait Proxy extends DictionaryPageHeader {
    protected def _underlying_DictionaryPageHeader: DictionaryPageHeader
    override def numValues: Int = _underlying_DictionaryPageHeader.numValues
    override def encoding: parquet.format.Encoding = _underlying_DictionaryPageHeader.encoding
    override def isSorted: _root_.scala.Option[Boolean] = _underlying_DictionaryPageHeader.isSorted
    override def _passthroughFields = _underlying_DictionaryPageHeader._passthroughFields
  }
}

/**
 * Prefer the companion object's [[parquet.format.DictionaryPageHeader.apply]]
 * for construction if you don't need to specify passthrough fields.
 */
trait DictionaryPageHeader
  extends ThriftStruct
  with _root_.scala.Product3[Int, parquet.format.Encoding, Option[Boolean]]
  with HasThriftStructCodec3[DictionaryPageHeader]
  with java.io.Serializable
{
  import DictionaryPageHeader._

  def numValues: Int
  def encoding: parquet.format.Encoding
  def isSorted: _root_.scala.Option[Boolean]

  def _passthroughFields: immutable$Map[Short, TFieldBlob] = immutable$Map.empty

  def _1 = numValues
  def _2 = encoding
  def _3 = isSorted

  def toTuple: _root_.scala.Tuple3[Int, parquet.format.Encoding, Option[Boolean]] = {
    (
      numValues,
      encoding,
      isSorted
    )
  }


  /**
   * Gets a field value encoded as a binary blob using TCompactProtocol.  If the specified field
   * is present in the passthrough map, that value is returned.  Otherwise, if the specified field
   * is known and not optional and set to None, then the field is serialized and returned.
   */
  def getFieldBlob(_fieldId: Short): _root_.scala.Option[TFieldBlob] = {
    lazy val _buff = new TMemoryBuffer(32)
    lazy val _oprot = new TCompactProtocol(_buff)
    _passthroughFields.get(_fieldId) match {
      case blob: _root_.scala.Some[TFieldBlob] => blob
      case _root_.scala.None => {
        val _fieldOpt: _root_.scala.Option[TField] =
          _fieldId match {
            case 1 =>
              if (true) {
                writeNumValuesValue(numValues, _oprot)
                _root_.scala.Some(DictionaryPageHeader.NumValuesField)
              } else {
                _root_.scala.None
              }
            case 2 =>
              if (encoding ne null) {
                writeEncodingValue(encoding, _oprot)
                _root_.scala.Some(DictionaryPageHeader.EncodingField)
              } else {
                _root_.scala.None
              }
            case 3 =>
              if (isSorted.isDefined) {
                writeIsSortedValue(isSorted.get, _oprot)
                _root_.scala.Some(DictionaryPageHeader.IsSortedField)
              } else {
                _root_.scala.None
              }
            case _ => _root_.scala.None
          }
        _fieldOpt match {
          case _root_.scala.Some(_field) =>
            _root_.scala.Some(TFieldBlob(_field, Buf.ByteArray.Owned(_buff.getArray())))
          case _root_.scala.None =>
            _root_.scala.None
        }
      }
    }
  }

  /**
   * Collects TCompactProtocol-encoded field values according to `getFieldBlob` into a map.
   */
  def getFieldBlobs(ids: TraversableOnce[Short]): immutable$Map[Short, TFieldBlob] =
    (ids flatMap { id => getFieldBlob(id) map { id -> _ } }).toMap

  /**
   * Sets a field using a TCompactProtocol-encoded binary blob.  If the field is a known
   * field, the blob is decoded and the field is set to the decoded value.  If the field
   * is unknown and passthrough fields are enabled, then the blob will be stored in
   * _passthroughFields.
   */
  def setField(_blob: TFieldBlob): DictionaryPageHeader = {
    var numValues: Int = this.numValues
    var encoding: parquet.format.Encoding = this.encoding
    var isSorted: _root_.scala.Option[Boolean] = this.isSorted
    var _passthroughFields = this._passthroughFields
    _blob.id match {
      case 1 =>
        numValues = readNumValuesValue(_blob.read)
      case 2 =>
        encoding = readEncodingValue(_blob.read)
      case 3 =>
        isSorted = _root_.scala.Some(readIsSortedValue(_blob.read))
      case _ => _passthroughFields += (_blob.id -> _blob)
    }
    new Immutable(
      numValues,
      encoding,
      isSorted,
      _passthroughFields
    )
  }

  /**
   * If the specified field is optional, it is set to None.  Otherwise, if the field is
   * known, it is reverted to its default value; if the field is unknown, it is removed
   * from the passthroughFields map, if present.
   */
  def unsetField(_fieldId: Short): DictionaryPageHeader = {
    var numValues: Int = this.numValues
    var encoding: parquet.format.Encoding = this.encoding
    var isSorted: _root_.scala.Option[Boolean] = this.isSorted

    _fieldId match {
      case 1 =>
        numValues = 0
      case 2 =>
        encoding = null
      case 3 =>
        isSorted = _root_.scala.None
      case _ =>
    }
    new Immutable(
      numValues,
      encoding,
      isSorted,
      _passthroughFields - _fieldId
    )
  }

  /**
   * If the specified field is optional, it is set to None.  Otherwise, if the field is
   * known, it is reverted to its default value; if the field is unknown, it is removed
   * from the passthroughFields map, if present.
   */
  def unsetNumValues: DictionaryPageHeader = unsetField(1)

  def unsetEncoding: DictionaryPageHeader = unsetField(2)

  def unsetIsSorted: DictionaryPageHeader = unsetField(3)


  override def write(_oprot: TProtocol): Unit = {
    DictionaryPageHeader.validate(this)
    _oprot.writeStructBegin(Struct)
    writeNumValuesField(numValues, _oprot)
    if (encoding ne null) writeEncodingField(encoding, _oprot)
    if (isSorted.isDefined) writeIsSortedField(isSorted.get, _oprot)
    if (_passthroughFields.nonEmpty) {
      _passthroughFields.values.foreach { _.write(_oprot) }
    }
    _oprot.writeFieldStop()
    _oprot.writeStructEnd()
  }

  def copy(
    numValues: Int = this.numValues,
    encoding: parquet.format.Encoding = this.encoding,
    isSorted: _root_.scala.Option[Boolean] = this.isSorted,
    _passthroughFields: immutable$Map[Short, TFieldBlob] = this._passthroughFields
  ): DictionaryPageHeader =
    new Immutable(
      numValues,
      encoding,
      isSorted,
      _passthroughFields
    )

  override def canEqual(other: Any): Boolean = other.isInstanceOf[DictionaryPageHeader]

  private def _equals(x: DictionaryPageHeader, y: DictionaryPageHeader): Boolean =
      x.productArity == y.productArity &&
      x.productIterator.sameElements(y.productIterator)

  override def equals(other: Any): Boolean =
    canEqual(other) &&
      _equals(this, other.asInstanceOf[DictionaryPageHeader]) &&
      _passthroughFields == other.asInstanceOf[DictionaryPageHeader]._passthroughFields

  override def hashCode: Int = _root_.scala.runtime.ScalaRunTime._hashCode(this)

  override def toString: String = _root_.scala.runtime.ScalaRunTime._toString(this)


  override def productArity: Int = 3

  override def productElement(n: Int): Any = n match {
    case 0 => this.numValues
    case 1 => this.encoding
    case 2 => this.isSorted
    case _ => throw new IndexOutOfBoundsException(n.toString)
  }

  override def productPrefix: String = "DictionaryPageHeader"

  def _codec: ThriftStructCodec3[DictionaryPageHeader] = DictionaryPageHeader
}

