/**
 * Generated by Scrooge
 *   version: 4.16.0-SNAPSHOT
 *   rev: eb110c820bcd2734b26023f24d636bf6d37511b3
 *   built at: 20170607-185808
 */
package parquet.format

import com.twitter.io.Buf
import com.twitter.scrooge.{
  HasThriftStructCodec3,
  LazyTProtocol,
  TFieldBlob,
  ThriftException,
  ThriftStruct,
  ThriftStructCodec3,
  ThriftStructFieldInfo,
  ThriftStructMetaData,
  ThriftUtil
}
import org.apache.thrift.protocol._
import org.apache.thrift.transport.{TMemoryBuffer, TTransport, TIOStreamTransport}
import java.io.ByteArrayInputStream
import java.nio.ByteBuffer
import java.util.Arrays
import java.util.concurrent.atomic.AtomicInteger
import scala.collection.immutable.{Map => immutable$Map}
import scala.collection.mutable.Builder
import scala.collection.mutable.{
  ArrayBuffer => mutable$ArrayBuffer, Buffer => mutable$Buffer,
  HashMap => mutable$HashMap, HashSet => mutable$HashSet}
import scala.collection.{Map, Set}

/**
 * statistics of a given page type and encoding
 */
object PageEncodingStats extends ThriftStructCodec3[PageEncodingStats] {
  val NoPassthroughFields: immutable$Map[Short, TFieldBlob] = immutable$Map.empty[Short, TFieldBlob]
  val Struct = new TStruct("PageEncodingStats")
  val PageTypeField = new TField("page_type", TType.ENUM, 1)
  val PageTypeFieldI32 = new TField("page_type", TType.I32, 1)
  val PageTypeFieldManifest = implicitly[Manifest[parquet.format.PageType]]
  val EncodingField = new TField("encoding", TType.ENUM, 2)
  val EncodingFieldI32 = new TField("encoding", TType.I32, 2)
  val EncodingFieldManifest = implicitly[Manifest[parquet.format.Encoding]]
  val CountField = new TField("count", TType.I32, 3)
  val CountFieldManifest = implicitly[Manifest[Int]]

  /**
   * Field information in declaration order.
   */
  lazy val fieldInfos: scala.List[ThriftStructFieldInfo] = scala.List[ThriftStructFieldInfo](
    new ThriftStructFieldInfo(
      PageTypeField,
      false,
      true,
      PageTypeFieldManifest,
      _root_.scala.None,
      _root_.scala.None,
      immutable$Map.empty[String, String],
      immutable$Map.empty[String, String],
      None
    ),
    new ThriftStructFieldInfo(
      EncodingField,
      false,
      true,
      EncodingFieldManifest,
      _root_.scala.None,
      _root_.scala.None,
      immutable$Map.empty[String, String],
      immutable$Map.empty[String, String],
      None
    ),
    new ThriftStructFieldInfo(
      CountField,
      false,
      true,
      CountFieldManifest,
      _root_.scala.None,
      _root_.scala.None,
      immutable$Map.empty[String, String],
      immutable$Map.empty[String, String],
      None
    )
  )

  lazy val structAnnotations: immutable$Map[String, String] =
    immutable$Map.empty[String, String]

  /**
   * Checks that all required fields are non-null.
   */
  def validate(_item: PageEncodingStats): Unit = {
    if (_item.pageType == null) throw new TProtocolException("Required field pageType cannot be null")
    if (_item.encoding == null) throw new TProtocolException("Required field encoding cannot be null")
  }

  def withoutPassthroughFields(original: PageEncodingStats): PageEncodingStats =
    new Immutable(
      pageType =
        {
          val field = original.pageType
          field
        },
      encoding =
        {
          val field = original.encoding
          field
        },
      count =
        {
          val field = original.count
          field
        }
    )

  override def encode(_item: PageEncodingStats, _oproto: TProtocol): Unit = {
    _item.write(_oproto)
  }


  private[this] def lazyDecode(_iprot: LazyTProtocol): PageEncodingStats = {

    var pageType: parquet.format.PageType = null
    var _got_pageType = false
    var encoding: parquet.format.Encoding = null
    var _got_encoding = false
    var count: Int = 0
    var _got_count = false

    var _passthroughFields: Builder[(Short, TFieldBlob), immutable$Map[Short, TFieldBlob]] = null
    var _done = false
    val _start_offset = _iprot.offset

    _iprot.readStructBegin()
    while (!_done) {
      val _field = _iprot.readFieldBegin()
      if (_field.`type` == TType.STOP) {
        _done = true
      } else {
        _field.id match {
          case 1 =>
            _field.`type` match {
              case TType.I32 | TType.ENUM =>
    
                pageType = readPageTypeValue(_iprot)
                _got_pageType = true
              case _actualType =>
                val _expectedType = TType.ENUM
                throw new TProtocolException(
                  "Received wrong type for field 'pageType' (expected=%s, actual=%s).".format(
                    ttypeToString(_expectedType),
                    ttypeToString(_actualType)
                  )
                )
            }
          case 2 =>
            _field.`type` match {
              case TType.I32 | TType.ENUM =>
    
                encoding = readEncodingValue(_iprot)
                _got_encoding = true
              case _actualType =>
                val _expectedType = TType.ENUM
                throw new TProtocolException(
                  "Received wrong type for field 'encoding' (expected=%s, actual=%s).".format(
                    ttypeToString(_expectedType),
                    ttypeToString(_actualType)
                  )
                )
            }
          case 3 =>
            _field.`type` match {
              case TType.I32 =>
    
                count = readCountValue(_iprot)
                _got_count = true
              case _actualType =>
                val _expectedType = TType.I32
                throw new TProtocolException(
                  "Received wrong type for field 'count' (expected=%s, actual=%s).".format(
                    ttypeToString(_expectedType),
                    ttypeToString(_actualType)
                  )
                )
            }
          case _ =>
            if (_passthroughFields == null)
              _passthroughFields = immutable$Map.newBuilder[Short, TFieldBlob]
            _passthroughFields += (_field.id -> TFieldBlob.read(_field, _iprot))
        }
        _iprot.readFieldEnd()
      }
    }
    _iprot.readStructEnd()

    if (!_got_pageType) throw new TProtocolException("Required field 'pageType' was not found in serialized data for struct PageEncodingStats")
    if (!_got_encoding) throw new TProtocolException("Required field 'encoding' was not found in serialized data for struct PageEncodingStats")
    if (!_got_count) throw new TProtocolException("Required field 'count' was not found in serialized data for struct PageEncodingStats")
    new LazyImmutable(
      _iprot,
      _iprot.buffer,
      _start_offset,
      _iprot.offset,
      pageType,
      encoding,
      count,
      if (_passthroughFields == null)
        NoPassthroughFields
      else
        _passthroughFields.result()
    )
  }

  override def decode(_iprot: TProtocol): PageEncodingStats =
    _iprot match {
      case i: LazyTProtocol => lazyDecode(i)
      case i => eagerDecode(i)
    }

  private[format] def eagerDecode(_iprot: TProtocol): PageEncodingStats = {
    var pageType: parquet.format.PageType = null
    var _got_pageType = false
    var encoding: parquet.format.Encoding = null
    var _got_encoding = false
    var count: Int = 0
    var _got_count = false
    var _passthroughFields: Builder[(Short, TFieldBlob), immutable$Map[Short, TFieldBlob]] = null
    var _done = false

    _iprot.readStructBegin()
    while (!_done) {
      val _field = _iprot.readFieldBegin()
      if (_field.`type` == TType.STOP) {
        _done = true
      } else {
        _field.id match {
          case 1 =>
            _field.`type` match {
              case TType.I32 | TType.ENUM =>
                pageType = readPageTypeValue(_iprot)
                _got_pageType = true
              case _actualType =>
                val _expectedType = TType.ENUM
                throw new TProtocolException(
                  "Received wrong type for field 'pageType' (expected=%s, actual=%s).".format(
                    ttypeToString(_expectedType),
                    ttypeToString(_actualType)
                  )
                )
            }
          case 2 =>
            _field.`type` match {
              case TType.I32 | TType.ENUM =>
                encoding = readEncodingValue(_iprot)
                _got_encoding = true
              case _actualType =>
                val _expectedType = TType.ENUM
                throw new TProtocolException(
                  "Received wrong type for field 'encoding' (expected=%s, actual=%s).".format(
                    ttypeToString(_expectedType),
                    ttypeToString(_actualType)
                  )
                )
            }
          case 3 =>
            _field.`type` match {
              case TType.I32 =>
                count = readCountValue(_iprot)
                _got_count = true
              case _actualType =>
                val _expectedType = TType.I32
                throw new TProtocolException(
                  "Received wrong type for field 'count' (expected=%s, actual=%s).".format(
                    ttypeToString(_expectedType),
                    ttypeToString(_actualType)
                  )
                )
            }
          case _ =>
            if (_passthroughFields == null)
              _passthroughFields = immutable$Map.newBuilder[Short, TFieldBlob]
            _passthroughFields += (_field.id -> TFieldBlob.read(_field, _iprot))
        }
        _iprot.readFieldEnd()
      }
    }
    _iprot.readStructEnd()

    if (!_got_pageType) throw new TProtocolException("Required field 'pageType' was not found in serialized data for struct PageEncodingStats")
    if (!_got_encoding) throw new TProtocolException("Required field 'encoding' was not found in serialized data for struct PageEncodingStats")
    if (!_got_count) throw new TProtocolException("Required field 'count' was not found in serialized data for struct PageEncodingStats")
    new Immutable(
      pageType,
      encoding,
      count,
      if (_passthroughFields == null)
        NoPassthroughFields
      else
        _passthroughFields.result()
    )
  }

  def apply(
    pageType: parquet.format.PageType,
    encoding: parquet.format.Encoding,
    count: Int
  ): PageEncodingStats =
    new Immutable(
      pageType,
      encoding,
      count
    )

  def unapply(_item: PageEncodingStats): _root_.scala.Option[_root_.scala.Tuple3[parquet.format.PageType, parquet.format.Encoding, Int]] = _root_.scala.Some(_item.toTuple)


  @inline private[format] def readPageTypeValue(_iprot: TProtocol): parquet.format.PageType = {
    parquet.format.PageType.getOrUnknown(_iprot.readI32())
  }

  @inline private def writePageTypeField(pageType_item: parquet.format.PageType, _oprot: TProtocol): Unit = {
    _oprot.writeFieldBegin(PageTypeFieldI32)
    writePageTypeValue(pageType_item, _oprot)
    _oprot.writeFieldEnd()
  }

  @inline private def writePageTypeValue(pageType_item: parquet.format.PageType, _oprot: TProtocol): Unit = {
    _oprot.writeI32(pageType_item.value)
  }

  @inline private[format] def readEncodingValue(_iprot: TProtocol): parquet.format.Encoding = {
    parquet.format.Encoding.getOrUnknown(_iprot.readI32())
  }

  @inline private def writeEncodingField(encoding_item: parquet.format.Encoding, _oprot: TProtocol): Unit = {
    _oprot.writeFieldBegin(EncodingFieldI32)
    writeEncodingValue(encoding_item, _oprot)
    _oprot.writeFieldEnd()
  }

  @inline private def writeEncodingValue(encoding_item: parquet.format.Encoding, _oprot: TProtocol): Unit = {
    _oprot.writeI32(encoding_item.value)
  }

  @inline private[format] def readCountValue(_iprot: TProtocol): Int = {
    _iprot.readI32()
  }

  @inline private def writeCountField(count_item: Int, _oprot: TProtocol): Unit = {
    _oprot.writeFieldBegin(CountField)
    writeCountValue(count_item, _oprot)
    _oprot.writeFieldEnd()
  }

  @inline private def writeCountValue(count_item: Int, _oprot: TProtocol): Unit = {
    _oprot.writeI32(count_item)
  }


  object Immutable extends ThriftStructCodec3[PageEncodingStats] {
    override def encode(_item: PageEncodingStats, _oproto: TProtocol): Unit = { _item.write(_oproto) }
    override def decode(_iprot: TProtocol): PageEncodingStats = PageEncodingStats.decode(_iprot)
    override lazy val metaData: ThriftStructMetaData[PageEncodingStats] = PageEncodingStats.metaData
  }

  /**
   * The default read-only implementation of PageEncodingStats.  You typically should not need to
   * directly reference this class; instead, use the PageEncodingStats.apply method to construct
   * new instances.
   */
  class Immutable(
      val pageType: parquet.format.PageType,
      val encoding: parquet.format.Encoding,
      val count: Int,
      override val _passthroughFields: immutable$Map[Short, TFieldBlob])
    extends PageEncodingStats {
    def this(
      pageType: parquet.format.PageType,
      encoding: parquet.format.Encoding,
      count: Int
    ) = this(
      pageType,
      encoding,
      count,
      Map.empty
    )
  }

  /**
   * This is another Immutable, this however keeps strings as lazy values that are lazily decoded from the backing
   * array byte on read.
   */
  private[this] class LazyImmutable(
      _proto: LazyTProtocol,
      _buf: Array[Byte],
      _start_offset: Int,
      _end_offset: Int,
      val pageType: parquet.format.PageType,
      val encoding: parquet.format.Encoding,
      val count: Int,
      override val _passthroughFields: immutable$Map[Short, TFieldBlob])
    extends PageEncodingStats {

    override def write(_oprot: TProtocol): Unit = {
      _oprot match {
        case i: LazyTProtocol => i.writeRaw(_buf, _start_offset, _end_offset - _start_offset)
        case _ => super.write(_oprot)
      }
    }


    /**
     * Override the super hash code to make it a lazy val rather than def.
     *
     * Calculating the hash code can be expensive, caching it where possible
     * can provide significant performance wins. (Key in a hash map for instance)
     * Usually not safe since the normal constructor will accept a mutable map or
     * set as an arg
     * Here however we control how the class is generated from serialized data.
     * With the class private and the contract that we throw away our mutable references
     * having the hash code lazy here is safe.
     */
    override lazy val hashCode = super.hashCode
  }

  /**
   * This Proxy trait allows you to extend the PageEncodingStats trait with additional state or
   * behavior and implement the read-only methods from PageEncodingStats using an underlying
   * instance.
   */
  trait Proxy extends PageEncodingStats {
    protected def _underlying_PageEncodingStats: PageEncodingStats
    override def pageType: parquet.format.PageType = _underlying_PageEncodingStats.pageType
    override def encoding: parquet.format.Encoding = _underlying_PageEncodingStats.encoding
    override def count: Int = _underlying_PageEncodingStats.count
    override def _passthroughFields = _underlying_PageEncodingStats._passthroughFields
  }
}

/**
 * Prefer the companion object's [[parquet.format.PageEncodingStats.apply]]
 * for construction if you don't need to specify passthrough fields.
 */
trait PageEncodingStats
  extends ThriftStruct
  with _root_.scala.Product3[parquet.format.PageType, parquet.format.Encoding, Int]
  with HasThriftStructCodec3[PageEncodingStats]
  with java.io.Serializable
{
  import PageEncodingStats._

  def pageType: parquet.format.PageType
  def encoding: parquet.format.Encoding
  def count: Int

  def _passthroughFields: immutable$Map[Short, TFieldBlob] = immutable$Map.empty

  def _1 = pageType
  def _2 = encoding
  def _3 = count

  def toTuple: _root_.scala.Tuple3[parquet.format.PageType, parquet.format.Encoding, Int] = {
    (
      pageType,
      encoding,
      count
    )
  }


  /**
   * Gets a field value encoded as a binary blob using TCompactProtocol.  If the specified field
   * is present in the passthrough map, that value is returned.  Otherwise, if the specified field
   * is known and not optional and set to None, then the field is serialized and returned.
   */
  def getFieldBlob(_fieldId: Short): _root_.scala.Option[TFieldBlob] = {
    lazy val _buff = new TMemoryBuffer(32)
    lazy val _oprot = new TCompactProtocol(_buff)
    _passthroughFields.get(_fieldId) match {
      case blob: _root_.scala.Some[TFieldBlob] => blob
      case _root_.scala.None => {
        val _fieldOpt: _root_.scala.Option[TField] =
          _fieldId match {
            case 1 =>
              if (pageType ne null) {
                writePageTypeValue(pageType, _oprot)
                _root_.scala.Some(PageEncodingStats.PageTypeField)
              } else {
                _root_.scala.None
              }
            case 2 =>
              if (encoding ne null) {
                writeEncodingValue(encoding, _oprot)
                _root_.scala.Some(PageEncodingStats.EncodingField)
              } else {
                _root_.scala.None
              }
            case 3 =>
              if (true) {
                writeCountValue(count, _oprot)
                _root_.scala.Some(PageEncodingStats.CountField)
              } else {
                _root_.scala.None
              }
            case _ => _root_.scala.None
          }
        _fieldOpt match {
          case _root_.scala.Some(_field) =>
            _root_.scala.Some(TFieldBlob(_field, Buf.ByteArray.Owned(_buff.getArray())))
          case _root_.scala.None =>
            _root_.scala.None
        }
      }
    }
  }

  /**
   * Collects TCompactProtocol-encoded field values according to `getFieldBlob` into a map.
   */
  def getFieldBlobs(ids: TraversableOnce[Short]): immutable$Map[Short, TFieldBlob] =
    (ids flatMap { id => getFieldBlob(id) map { id -> _ } }).toMap

  /**
   * Sets a field using a TCompactProtocol-encoded binary blob.  If the field is a known
   * field, the blob is decoded and the field is set to the decoded value.  If the field
   * is unknown and passthrough fields are enabled, then the blob will be stored in
   * _passthroughFields.
   */
  def setField(_blob: TFieldBlob): PageEncodingStats = {
    var pageType: parquet.format.PageType = this.pageType
    var encoding: parquet.format.Encoding = this.encoding
    var count: Int = this.count
    var _passthroughFields = this._passthroughFields
    _blob.id match {
      case 1 =>
        pageType = readPageTypeValue(_blob.read)
      case 2 =>
        encoding = readEncodingValue(_blob.read)
      case 3 =>
        count = readCountValue(_blob.read)
      case _ => _passthroughFields += (_blob.id -> _blob)
    }
    new Immutable(
      pageType,
      encoding,
      count,
      _passthroughFields
    )
  }

  /**
   * If the specified field is optional, it is set to None.  Otherwise, if the field is
   * known, it is reverted to its default value; if the field is unknown, it is removed
   * from the passthroughFields map, if present.
   */
  def unsetField(_fieldId: Short): PageEncodingStats = {
    var pageType: parquet.format.PageType = this.pageType
    var encoding: parquet.format.Encoding = this.encoding
    var count: Int = this.count

    _fieldId match {
      case 1 =>
        pageType = null
      case 2 =>
        encoding = null
      case 3 =>
        count = 0
      case _ =>
    }
    new Immutable(
      pageType,
      encoding,
      count,
      _passthroughFields - _fieldId
    )
  }

  /**
   * If the specified field is optional, it is set to None.  Otherwise, if the field is
   * known, it is reverted to its default value; if the field is unknown, it is removed
   * from the passthroughFields map, if present.
   */
  def unsetPageType: PageEncodingStats = unsetField(1)

  def unsetEncoding: PageEncodingStats = unsetField(2)

  def unsetCount: PageEncodingStats = unsetField(3)


  override def write(_oprot: TProtocol): Unit = {
    PageEncodingStats.validate(this)
    _oprot.writeStructBegin(Struct)
    if (pageType ne null) writePageTypeField(pageType, _oprot)
    if (encoding ne null) writeEncodingField(encoding, _oprot)
    writeCountField(count, _oprot)
    if (_passthroughFields.nonEmpty) {
      _passthroughFields.values.foreach { _.write(_oprot) }
    }
    _oprot.writeFieldStop()
    _oprot.writeStructEnd()
  }

  def copy(
    pageType: parquet.format.PageType = this.pageType,
    encoding: parquet.format.Encoding = this.encoding,
    count: Int = this.count,
    _passthroughFields: immutable$Map[Short, TFieldBlob] = this._passthroughFields
  ): PageEncodingStats =
    new Immutable(
      pageType,
      encoding,
      count,
      _passthroughFields
    )

  override def canEqual(other: Any): Boolean = other.isInstanceOf[PageEncodingStats]

  private def _equals(x: PageEncodingStats, y: PageEncodingStats): Boolean =
      x.productArity == y.productArity &&
      x.productIterator.sameElements(y.productIterator)

  override def equals(other: Any): Boolean =
    canEqual(other) &&
      _equals(this, other.asInstanceOf[PageEncodingStats]) &&
      _passthroughFields == other.asInstanceOf[PageEncodingStats]._passthroughFields

  override def hashCode: Int = _root_.scala.runtime.ScalaRunTime._hashCode(this)

  override def toString: String = _root_.scala.runtime.ScalaRunTime._toString(this)


  override def productArity: Int = 3

  override def productElement(n: Int): Any = n match {
    case 0 => this.pageType
    case 1 => this.encoding
    case 2 => this.count
    case _ => throw new IndexOutOfBoundsException(n.toString)
  }

  override def productPrefix: String = "PageEncodingStats"

  def _codec: ThriftStructCodec3[PageEncodingStats] = PageEncodingStats
}

