/**
 * Generated by Scrooge
 *   version: 4.16.0-SNAPSHOT
 *   rev: eb110c820bcd2734b26023f24d636bf6d37511b3
 *   built at: 20170607-185808
 */
package parquet.format

import com.twitter.io.Buf
import com.twitter.scrooge.{
  HasThriftStructCodec3,
  LazyTProtocol,
  TFieldBlob,
  ThriftException,
  ThriftStruct,
  ThriftStructCodec3,
  ThriftStructFieldInfo,
  ThriftStructMetaData,
  ThriftUtil
}
import org.apache.thrift.protocol._
import org.apache.thrift.transport.{TMemoryBuffer, TTransport, TIOStreamTransport}
import java.io.ByteArrayInputStream
import java.nio.ByteBuffer
import java.util.Arrays
import java.util.concurrent.atomic.AtomicInteger
import scala.collection.immutable.{Map => immutable$Map}
import scala.collection.mutable.Builder
import scala.collection.mutable.{
  ArrayBuffer => mutable$ArrayBuffer, Buffer => mutable$Buffer,
  HashMap => mutable$HashMap, HashSet => mutable$HashSet}
import scala.collection.{Map, Set}

/**
 * Wrapper struct to specify sort order
 */
object SortingColumn extends ThriftStructCodec3[SortingColumn] {
  val NoPassthroughFields: immutable$Map[Short, TFieldBlob] = immutable$Map.empty[Short, TFieldBlob]
  val Struct = new TStruct("SortingColumn")
  val ColumnIdxField = new TField("column_idx", TType.I32, 1)
  val ColumnIdxFieldManifest = implicitly[Manifest[Int]]
  val DescendingField = new TField("descending", TType.BOOL, 2)
  val DescendingFieldManifest = implicitly[Manifest[Boolean]]
  val NullsFirstField = new TField("nulls_first", TType.BOOL, 3)
  val NullsFirstFieldManifest = implicitly[Manifest[Boolean]]

  /**
   * Field information in declaration order.
   */
  lazy val fieldInfos: scala.List[ThriftStructFieldInfo] = scala.List[ThriftStructFieldInfo](
    new ThriftStructFieldInfo(
      ColumnIdxField,
      false,
      true,
      ColumnIdxFieldManifest,
      _root_.scala.None,
      _root_.scala.None,
      immutable$Map.empty[String, String],
      immutable$Map.empty[String, String],
      None
    ),
    new ThriftStructFieldInfo(
      DescendingField,
      false,
      true,
      DescendingFieldManifest,
      _root_.scala.None,
      _root_.scala.None,
      immutable$Map.empty[String, String],
      immutable$Map.empty[String, String],
      None
    ),
    new ThriftStructFieldInfo(
      NullsFirstField,
      false,
      true,
      NullsFirstFieldManifest,
      _root_.scala.None,
      _root_.scala.None,
      immutable$Map.empty[String, String],
      immutable$Map.empty[String, String],
      None
    )
  )

  lazy val structAnnotations: immutable$Map[String, String] =
    immutable$Map.empty[String, String]

  /**
   * Checks that all required fields are non-null.
   */
  def validate(_item: SortingColumn): Unit = {
  }

  def withoutPassthroughFields(original: SortingColumn): SortingColumn =
    new Immutable(
      columnIdx =
        {
          val field = original.columnIdx
          field
        },
      descending =
        {
          val field = original.descending
          field
        },
      nullsFirst =
        {
          val field = original.nullsFirst
          field
        }
    )

  override def encode(_item: SortingColumn, _oproto: TProtocol): Unit = {
    _item.write(_oproto)
  }


  private[this] def lazyDecode(_iprot: LazyTProtocol): SortingColumn = {

    var columnIdx: Int = 0
    var _got_columnIdx = false
    var descending: Boolean = false
    var _got_descending = false
    var nullsFirst: Boolean = false
    var _got_nullsFirst = false

    var _passthroughFields: Builder[(Short, TFieldBlob), immutable$Map[Short, TFieldBlob]] = null
    var _done = false
    val _start_offset = _iprot.offset

    _iprot.readStructBegin()
    while (!_done) {
      val _field = _iprot.readFieldBegin()
      if (_field.`type` == TType.STOP) {
        _done = true
      } else {
        _field.id match {
          case 1 =>
            _field.`type` match {
              case TType.I32 =>
    
                columnIdx = readColumnIdxValue(_iprot)
                _got_columnIdx = true
              case _actualType =>
                val _expectedType = TType.I32
                throw new TProtocolException(
                  "Received wrong type for field 'columnIdx' (expected=%s, actual=%s).".format(
                    ttypeToString(_expectedType),
                    ttypeToString(_actualType)
                  )
                )
            }
          case 2 =>
            _field.`type` match {
              case TType.BOOL =>
    
                descending = readDescendingValue(_iprot)
                _got_descending = true
              case _actualType =>
                val _expectedType = TType.BOOL
                throw new TProtocolException(
                  "Received wrong type for field 'descending' (expected=%s, actual=%s).".format(
                    ttypeToString(_expectedType),
                    ttypeToString(_actualType)
                  )
                )
            }
          case 3 =>
            _field.`type` match {
              case TType.BOOL =>
    
                nullsFirst = readNullsFirstValue(_iprot)
                _got_nullsFirst = true
              case _actualType =>
                val _expectedType = TType.BOOL
                throw new TProtocolException(
                  "Received wrong type for field 'nullsFirst' (expected=%s, actual=%s).".format(
                    ttypeToString(_expectedType),
                    ttypeToString(_actualType)
                  )
                )
            }
          case _ =>
            if (_passthroughFields == null)
              _passthroughFields = immutable$Map.newBuilder[Short, TFieldBlob]
            _passthroughFields += (_field.id -> TFieldBlob.read(_field, _iprot))
        }
        _iprot.readFieldEnd()
      }
    }
    _iprot.readStructEnd()

    if (!_got_columnIdx) throw new TProtocolException("Required field 'columnIdx' was not found in serialized data for struct SortingColumn")
    if (!_got_descending) throw new TProtocolException("Required field 'descending' was not found in serialized data for struct SortingColumn")
    if (!_got_nullsFirst) throw new TProtocolException("Required field 'nullsFirst' was not found in serialized data for struct SortingColumn")
    new LazyImmutable(
      _iprot,
      _iprot.buffer,
      _start_offset,
      _iprot.offset,
      columnIdx,
      descending,
      nullsFirst,
      if (_passthroughFields == null)
        NoPassthroughFields
      else
        _passthroughFields.result()
    )
  }

  override def decode(_iprot: TProtocol): SortingColumn =
    _iprot match {
      case i: LazyTProtocol => lazyDecode(i)
      case i => eagerDecode(i)
    }

  private[format] def eagerDecode(_iprot: TProtocol): SortingColumn = {
    var columnIdx: Int = 0
    var _got_columnIdx = false
    var descending: Boolean = false
    var _got_descending = false
    var nullsFirst: Boolean = false
    var _got_nullsFirst = false
    var _passthroughFields: Builder[(Short, TFieldBlob), immutable$Map[Short, TFieldBlob]] = null
    var _done = false

    _iprot.readStructBegin()
    while (!_done) {
      val _field = _iprot.readFieldBegin()
      if (_field.`type` == TType.STOP) {
        _done = true
      } else {
        _field.id match {
          case 1 =>
            _field.`type` match {
              case TType.I32 =>
                columnIdx = readColumnIdxValue(_iprot)
                _got_columnIdx = true
              case _actualType =>
                val _expectedType = TType.I32
                throw new TProtocolException(
                  "Received wrong type for field 'columnIdx' (expected=%s, actual=%s).".format(
                    ttypeToString(_expectedType),
                    ttypeToString(_actualType)
                  )
                )
            }
          case 2 =>
            _field.`type` match {
              case TType.BOOL =>
                descending = readDescendingValue(_iprot)
                _got_descending = true
              case _actualType =>
                val _expectedType = TType.BOOL
                throw new TProtocolException(
                  "Received wrong type for field 'descending' (expected=%s, actual=%s).".format(
                    ttypeToString(_expectedType),
                    ttypeToString(_actualType)
                  )
                )
            }
          case 3 =>
            _field.`type` match {
              case TType.BOOL =>
                nullsFirst = readNullsFirstValue(_iprot)
                _got_nullsFirst = true
              case _actualType =>
                val _expectedType = TType.BOOL
                throw new TProtocolException(
                  "Received wrong type for field 'nullsFirst' (expected=%s, actual=%s).".format(
                    ttypeToString(_expectedType),
                    ttypeToString(_actualType)
                  )
                )
            }
          case _ =>
            if (_passthroughFields == null)
              _passthroughFields = immutable$Map.newBuilder[Short, TFieldBlob]
            _passthroughFields += (_field.id -> TFieldBlob.read(_field, _iprot))
        }
        _iprot.readFieldEnd()
      }
    }
    _iprot.readStructEnd()

    if (!_got_columnIdx) throw new TProtocolException("Required field 'columnIdx' was not found in serialized data for struct SortingColumn")
    if (!_got_descending) throw new TProtocolException("Required field 'descending' was not found in serialized data for struct SortingColumn")
    if (!_got_nullsFirst) throw new TProtocolException("Required field 'nullsFirst' was not found in serialized data for struct SortingColumn")
    new Immutable(
      columnIdx,
      descending,
      nullsFirst,
      if (_passthroughFields == null)
        NoPassthroughFields
      else
        _passthroughFields.result()
    )
  }

  def apply(
    columnIdx: Int,
    descending: Boolean,
    nullsFirst: Boolean
  ): SortingColumn =
    new Immutable(
      columnIdx,
      descending,
      nullsFirst
    )

  def unapply(_item: SortingColumn): _root_.scala.Option[_root_.scala.Tuple3[Int, Boolean, Boolean]] = _root_.scala.Some(_item.toTuple)


  @inline private[format] def readColumnIdxValue(_iprot: TProtocol): Int = {
    _iprot.readI32()
  }

  @inline private def writeColumnIdxField(columnIdx_item: Int, _oprot: TProtocol): Unit = {
    _oprot.writeFieldBegin(ColumnIdxField)
    writeColumnIdxValue(columnIdx_item, _oprot)
    _oprot.writeFieldEnd()
  }

  @inline private def writeColumnIdxValue(columnIdx_item: Int, _oprot: TProtocol): Unit = {
    _oprot.writeI32(columnIdx_item)
  }

  @inline private[format] def readDescendingValue(_iprot: TProtocol): Boolean = {
    _iprot.readBool()
  }

  @inline private def writeDescendingField(descending_item: Boolean, _oprot: TProtocol): Unit = {
    _oprot.writeFieldBegin(DescendingField)
    writeDescendingValue(descending_item, _oprot)
    _oprot.writeFieldEnd()
  }

  @inline private def writeDescendingValue(descending_item: Boolean, _oprot: TProtocol): Unit = {
    _oprot.writeBool(descending_item)
  }

  @inline private[format] def readNullsFirstValue(_iprot: TProtocol): Boolean = {
    _iprot.readBool()
  }

  @inline private def writeNullsFirstField(nullsFirst_item: Boolean, _oprot: TProtocol): Unit = {
    _oprot.writeFieldBegin(NullsFirstField)
    writeNullsFirstValue(nullsFirst_item, _oprot)
    _oprot.writeFieldEnd()
  }

  @inline private def writeNullsFirstValue(nullsFirst_item: Boolean, _oprot: TProtocol): Unit = {
    _oprot.writeBool(nullsFirst_item)
  }


  object Immutable extends ThriftStructCodec3[SortingColumn] {
    override def encode(_item: SortingColumn, _oproto: TProtocol): Unit = { _item.write(_oproto) }
    override def decode(_iprot: TProtocol): SortingColumn = SortingColumn.decode(_iprot)
    override lazy val metaData: ThriftStructMetaData[SortingColumn] = SortingColumn.metaData
  }

  /**
   * The default read-only implementation of SortingColumn.  You typically should not need to
   * directly reference this class; instead, use the SortingColumn.apply method to construct
   * new instances.
   */
  class Immutable(
      val columnIdx: Int,
      val descending: Boolean,
      val nullsFirst: Boolean,
      override val _passthroughFields: immutable$Map[Short, TFieldBlob])
    extends SortingColumn {
    def this(
      columnIdx: Int,
      descending: Boolean,
      nullsFirst: Boolean
    ) = this(
      columnIdx,
      descending,
      nullsFirst,
      Map.empty
    )
  }

  /**
   * This is another Immutable, this however keeps strings as lazy values that are lazily decoded from the backing
   * array byte on read.
   */
  private[this] class LazyImmutable(
      _proto: LazyTProtocol,
      _buf: Array[Byte],
      _start_offset: Int,
      _end_offset: Int,
      val columnIdx: Int,
      val descending: Boolean,
      val nullsFirst: Boolean,
      override val _passthroughFields: immutable$Map[Short, TFieldBlob])
    extends SortingColumn {

    override def write(_oprot: TProtocol): Unit = {
      _oprot match {
        case i: LazyTProtocol => i.writeRaw(_buf, _start_offset, _end_offset - _start_offset)
        case _ => super.write(_oprot)
      }
    }


    /**
     * Override the super hash code to make it a lazy val rather than def.
     *
     * Calculating the hash code can be expensive, caching it where possible
     * can provide significant performance wins. (Key in a hash map for instance)
     * Usually not safe since the normal constructor will accept a mutable map or
     * set as an arg
     * Here however we control how the class is generated from serialized data.
     * With the class private and the contract that we throw away our mutable references
     * having the hash code lazy here is safe.
     */
    override lazy val hashCode = super.hashCode
  }

  /**
   * This Proxy trait allows you to extend the SortingColumn trait with additional state or
   * behavior and implement the read-only methods from SortingColumn using an underlying
   * instance.
   */
  trait Proxy extends SortingColumn {
    protected def _underlying_SortingColumn: SortingColumn
    override def columnIdx: Int = _underlying_SortingColumn.columnIdx
    override def descending: Boolean = _underlying_SortingColumn.descending
    override def nullsFirst: Boolean = _underlying_SortingColumn.nullsFirst
    override def _passthroughFields = _underlying_SortingColumn._passthroughFields
  }
}

/**
 * Prefer the companion object's [[parquet.format.SortingColumn.apply]]
 * for construction if you don't need to specify passthrough fields.
 */
trait SortingColumn
  extends ThriftStruct
  with _root_.scala.Product3[Int, Boolean, Boolean]
  with HasThriftStructCodec3[SortingColumn]
  with java.io.Serializable
{
  import SortingColumn._

  def columnIdx: Int
  def descending: Boolean
  def nullsFirst: Boolean

  def _passthroughFields: immutable$Map[Short, TFieldBlob] = immutable$Map.empty

  def _1 = columnIdx
  def _2 = descending
  def _3 = nullsFirst

  def toTuple: _root_.scala.Tuple3[Int, Boolean, Boolean] = {
    (
      columnIdx,
      descending,
      nullsFirst
    )
  }


  /**
   * Gets a field value encoded as a binary blob using TCompactProtocol.  If the specified field
   * is present in the passthrough map, that value is returned.  Otherwise, if the specified field
   * is known and not optional and set to None, then the field is serialized and returned.
   */
  def getFieldBlob(_fieldId: Short): _root_.scala.Option[TFieldBlob] = {
    lazy val _buff = new TMemoryBuffer(32)
    lazy val _oprot = new TCompactProtocol(_buff)
    _passthroughFields.get(_fieldId) match {
      case blob: _root_.scala.Some[TFieldBlob] => blob
      case _root_.scala.None => {
        val _fieldOpt: _root_.scala.Option[TField] =
          _fieldId match {
            case 1 =>
              if (true) {
                writeColumnIdxValue(columnIdx, _oprot)
                _root_.scala.Some(SortingColumn.ColumnIdxField)
              } else {
                _root_.scala.None
              }
            case 2 =>
              if (true) {
                writeDescendingValue(descending, _oprot)
                _root_.scala.Some(SortingColumn.DescendingField)
              } else {
                _root_.scala.None
              }
            case 3 =>
              if (true) {
                writeNullsFirstValue(nullsFirst, _oprot)
                _root_.scala.Some(SortingColumn.NullsFirstField)
              } else {
                _root_.scala.None
              }
            case _ => _root_.scala.None
          }
        _fieldOpt match {
          case _root_.scala.Some(_field) =>
            _root_.scala.Some(TFieldBlob(_field, Buf.ByteArray.Owned(_buff.getArray())))
          case _root_.scala.None =>
            _root_.scala.None
        }
      }
    }
  }

  /**
   * Collects TCompactProtocol-encoded field values according to `getFieldBlob` into a map.
   */
  def getFieldBlobs(ids: TraversableOnce[Short]): immutable$Map[Short, TFieldBlob] =
    (ids flatMap { id => getFieldBlob(id) map { id -> _ } }).toMap

  /**
   * Sets a field using a TCompactProtocol-encoded binary blob.  If the field is a known
   * field, the blob is decoded and the field is set to the decoded value.  If the field
   * is unknown and passthrough fields are enabled, then the blob will be stored in
   * _passthroughFields.
   */
  def setField(_blob: TFieldBlob): SortingColumn = {
    var columnIdx: Int = this.columnIdx
    var descending: Boolean = this.descending
    var nullsFirst: Boolean = this.nullsFirst
    var _passthroughFields = this._passthroughFields
    _blob.id match {
      case 1 =>
        columnIdx = readColumnIdxValue(_blob.read)
      case 2 =>
        descending = readDescendingValue(_blob.read)
      case 3 =>
        nullsFirst = readNullsFirstValue(_blob.read)
      case _ => _passthroughFields += (_blob.id -> _blob)
    }
    new Immutable(
      columnIdx,
      descending,
      nullsFirst,
      _passthroughFields
    )
  }

  /**
   * If the specified field is optional, it is set to None.  Otherwise, if the field is
   * known, it is reverted to its default value; if the field is unknown, it is removed
   * from the passthroughFields map, if present.
   */
  def unsetField(_fieldId: Short): SortingColumn = {
    var columnIdx: Int = this.columnIdx
    var descending: Boolean = this.descending
    var nullsFirst: Boolean = this.nullsFirst

    _fieldId match {
      case 1 =>
        columnIdx = 0
      case 2 =>
        descending = false
      case 3 =>
        nullsFirst = false
      case _ =>
    }
    new Immutable(
      columnIdx,
      descending,
      nullsFirst,
      _passthroughFields - _fieldId
    )
  }

  /**
   * If the specified field is optional, it is set to None.  Otherwise, if the field is
   * known, it is reverted to its default value; if the field is unknown, it is removed
   * from the passthroughFields map, if present.
   */
  def unsetColumnIdx: SortingColumn = unsetField(1)

  def unsetDescending: SortingColumn = unsetField(2)

  def unsetNullsFirst: SortingColumn = unsetField(3)


  override def write(_oprot: TProtocol): Unit = {
    SortingColumn.validate(this)
    _oprot.writeStructBegin(Struct)
    writeColumnIdxField(columnIdx, _oprot)
    writeDescendingField(descending, _oprot)
    writeNullsFirstField(nullsFirst, _oprot)
    if (_passthroughFields.nonEmpty) {
      _passthroughFields.values.foreach { _.write(_oprot) }
    }
    _oprot.writeFieldStop()
    _oprot.writeStructEnd()
  }

  def copy(
    columnIdx: Int = this.columnIdx,
    descending: Boolean = this.descending,
    nullsFirst: Boolean = this.nullsFirst,
    _passthroughFields: immutable$Map[Short, TFieldBlob] = this._passthroughFields
  ): SortingColumn =
    new Immutable(
      columnIdx,
      descending,
      nullsFirst,
      _passthroughFields
    )

  override def canEqual(other: Any): Boolean = other.isInstanceOf[SortingColumn]

  private def _equals(x: SortingColumn, y: SortingColumn): Boolean =
      x.productArity == y.productArity &&
      x.productIterator.sameElements(y.productIterator)

  override def equals(other: Any): Boolean =
    canEqual(other) &&
      _equals(this, other.asInstanceOf[SortingColumn]) &&
      _passthroughFields == other.asInstanceOf[SortingColumn]._passthroughFields

  override def hashCode: Int = _root_.scala.runtime.ScalaRunTime._hashCode(this)

  override def toString: String = _root_.scala.runtime.ScalaRunTime._toString(this)


  override def productArity: Int = 3

  override def productElement(n: Int): Any = n match {
    case 0 => this.columnIdx
    case 1 => this.descending
    case 2 => this.nullsFirst
    case _ => throw new IndexOutOfBoundsException(n.toString)
  }

  override def productPrefix: String = "SortingColumn"

  def _codec: ThriftStructCodec3[SortingColumn] = SortingColumn
}

